#!/usr/bin/env python

from mbot_objects_mapping_ros import mbot_objects_mapping as objects_mapping_class
import rospy

if __name__ == '__main__':

    # Initiating ros node
    rospy.init_node('mbot_objects_mapping', anonymous=True)

    # Instantiating ObjectsMapping object
    objects_mapping = objects_mapping_class.ObjectsMapping()

    objects_mapping.loop()
